import crypto from 'node:crypto';
const normalize=value=>String(value||'').normalize('NFKC').toUpperCase().replace(/[\s\-\u2010-\u2015\u200B-\u200D\uFEFF]/g,'');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const pointer=o=>({__type:'Pointer',className:o.className,objectId:o.id});
const failures=new Map();
export default function configureInvitations({serial,authorize,member,role,validNif,privateACL}){
 const prefix=new URL(Parse.serverURL).pathname.replace(/\/$/,'');
 async function commit(requests){const result=await Parse._request('POST','batch',{transaction:true,requests},{useMasterKey:true});const rows=result.results||result;const failed=Array.isArray(rows)&&rows.find(r=>r.error);if(failed)throw new Error('No se pudo completar la invitación. Vuelve a intentarlo.');}
 Parse.Cloud.define('createInvitation',async r=>{
 await authorize(r.user,true);const label=String(r.params.label||'').trim();if(label.length>100)throw new Error('La referencia no puede superar 100 caracteres.');
 const code='VAC-'+crypto.randomBytes(12).toString('hex').toUpperCase().match(/.{4}/g).join('-');const expiresAt=new Date(Date.now()+7*86400000);const invitation=new Parse.Object('Invitation');invitation.set({tokenHash:hash(normalize(code)),label,expiresAt,createdBy:r.user});const acl=new Parse.ACL();acl.setRoleReadAccess('Administradores',true);invitation.setACL(acl);await invitation.save(null,{useMasterKey:true});return {id:invitation.id,code,expiresAt:expiresAt.toISOString()};
 });
 Parse.Cloud.define('listInvitations',async r=>{await authorize(r.user,true);const rows=await new Parse.Query('Invitation').descending('createdAt').include('usedBy').limit(500).find({useMasterKey:true});return rows.map(o=>({id:o.id,label:o.get('label'),createdAt:o.createdAt.toISOString(),expiresAt:o.get('expiresAt').toISOString(),usedAt:o.get('usedAt')?.toISOString()||'',email:o.get('usedBy')?.get('email')||'',status:o.get('revokedAt')?(o.get('usedBy')?'Acceso retirado':'Anulado'):o.get('usedBy')?'Utilizado':o.get('expiresAt')<new Date()?'Caducado':'Disponible'}));});
 Parse.Cloud.define('redeemInvitation',r=>serial(async()=>{
 if(!r.user)throw new Error('Inicia sesión o crea una cuenta para usar la invitación.');
 const nif=String(r.params.nif||'').trim().toUpperCase(),code=normalize(r.params.code);if(!validNif(nif))throw new Error('Introduce un NIF o NIE válido.');if(!/^VAC[A-F0-9]{24}$/.test(code))throw new Error('El código de invitación no es válido.');
 const freshUser=await new Parse.Query(Parse.User).get(r.user.id,{useMasterKey:true});
 if(freshUser.get('emailVerified')!==true&&!freshUser.get('authData')?.google)throw new Error('Verifica tu correo antes de canjear la invitación. No necesitas aprobación del administrador.');
 if(await member(r.user,'Profesionales'))return {ok:true};
 const attempt=failures.get(r.user.id);if(attempt&&attempt.until>Date.now()&&attempt.count>=5)throw new Error('Demasiados intentos. Espera 15 minutos antes de volver a probar.');
 const inv=await new Parse.Query('Invitation').equalTo('tokenHash',hash(code)).first({useMasterKey:true});
 if(!inv||inv.get('revokedAt')||(inv.get('usedBy')&&inv.get('usedBy').id!==r.user.id)||(!inv.get('usedBy')&&inv.get('expiresAt')<new Date())){const current=attempt&&attempt.until>Date.now()?attempt:{count:0,until:Date.now()+15*60000};failures.set(r.user.id,{count:current.count+1,until:current.until});throw new Error(!inv?'No se encuentra el código. Copia únicamente el código completo VAC-… de la invitación.':inv.get('revokedAt')?'Esta invitación está anulada. Solicita un código nuevo.':inv.get('usedBy')?'Este código pertenece a otra cuenta. Inicia sesión con la cuenta que lo canjeó o solicita otro.':'El código ha caducado. Solicita otro.');}
 const [professional,staff]=await Promise.all([new Parse.Query('Professional').equalTo('user',r.user).first({useMasterKey:true}),role('Profesionales')]);if(!staff)throw new Error('El acceso de profesionales no está configurado. Contacta con la persona que te invitó.');
 const acl=privateACL();acl.setReadAccess(r.user,true);acl.setRoleReadAccess('Administradores',true);const body={user:pointer(r.user),nif,email:r.user.get('email')||r.user.get('username'),ACL:acl.toJSON()};
 await commit([{method:professional?'PUT':'POST',path:`${prefix}/classes/Professional${professional?'/'+professional.id:''}`,body},{method:'PUT',path:`${prefix}/classes/_Role/${staff.id}`,body:{users:{__op:'AddRelation',objects:[pointer(r.user)]}}},{method:'PUT',path:`${prefix}/classes/Invitation/${inv.id}`,body:{usedBy:pointer(r.user),usedAt:{__type:'Date',iso:new Date().toISOString()}}}]);failures.delete(r.user.id);return {ok:true};
 }).catch(e=>({ok:false,message:e.message||'No se pudo canjear la invitación.'})));
 Parse.Cloud.define('cancelInvitation',r=>serial(async()=>{await authorize(r.user,true);const invitation=await new Parse.Query('Invitation').get(r.params.id,{useMasterKey:true});if(invitation.get('usedBy'))throw new Error('El código ya fue utilizado. Para retirar el acceso, usa la lista de personas con acceso.');invitation.set({revokedAt:new Date(),revokedBy:r.user});await invitation.save(null,{useMasterKey:true});return true;}));
 Parse.Cloud.define('revokeInvitedUser',r=>serial(async()=>{await authorize(r.user,true);const professional=await new Parse.Query('Professional').get(r.params.id,{useMasterKey:true}),user=professional.get('user');if(await member(user,'Administradores'))throw new Error('No se puede retirar el acceso a una cuenta administradora.');const [staff,invitations]=await Promise.all([role('Profesionales'),new Parse.Query('Invitation').equalTo('usedBy',user).find({useMasterKey:true})]);if(!staff)return true;await commit([{method:'PUT',path:`${prefix}/classes/_Role/${staff.id}`,body:{users:{__op:'RemoveRelation',objects:[pointer(user)]}}},...invitations.map(o=>({method:'PUT',path:`${prefix}/classes/Invitation/${o.id}`,body:{revokedAt:{__type:'Date',iso:new Date().toISOString()},revokedBy:pointer(r.user)}}))]);return true;}));
}
