const W=['Nevera 2B','Nevera 3B','Cajón consulta'];
const ptr=o=>({__type:'Pointer',className:o.className,objectId:o.id});
const date=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
export default function configureChanges({serial,integer,acl,authorize,profile}){
 const prefix=new URL(Parse.serverURL).pathname.replace(/\/$/,'');
 const update=(o,body)=>({method:'PUT',path:`${prefix}/classes/${o.className}/${o.id}`,body});
 const remove=o=>({method:'DELETE',path:`${prefix}/classes/${o.className}/${o.id}`});
 const create=(className,body)=>({method:'POST',path:`${prefix}/classes/${className}`,body:{...body,ACL:acl().toJSON()}});
 async function commit(requests){if(!requests.length)return;const result=await Parse._request('POST','batch',{transaction:true,requests},{useMasterKey:true});const rows=result.results||result;const error=Array.isArray(rows)&&rows.find(r=>r.error);if(error)throw new Error(error.error.error||'No se pudo guardar. Ningún cambio ha sido aplicado.');}
 function effect(m){const value=typeof m.get==='function'?m.attributes:m,out=Object.fromEntries(W.map(w=>[w,0]));if(['initial','in'].includes(value.type))out[value.destination]+=value.quantity;else if(value.type==='transfer'){out[value.source]-=value.quantity;out[value.destination]+=value.quantity;}else out[value.source]-=value.quantity;return out;}
 function adjusted(lot,deltas){const stocks={...lot.get('stocks')};for(const w of W){stocks[w]=(stocks[w]||0)+(deltas[w]||0);if(!integer(stocks[w]))throw new Error(`La corrección dejaría stock negativo o inválido en ${w}. Corrige primero los movimientos posteriores que usan esas unidades.`);}return stocks;}
 const audit=(user,action,record)=>create('RecordChange',{action,recordClass:record.className,recordId:record.id,actor:ptr(user),previousQuantity:record.get('quantity')||0});
 async function adjustReceipt(receipt,newQty,requests){const line=await new Parse.Query('OrderLine').include('order').get(receipt.get('line').id,{useMasterKey:true});const order=line.get('order');const qty=line.get('received')-receipt.get('quantity')+newQty;if(qty<0||qty>line.get('quantity'))throw new Error('La nueva recepción supera las unidades pedidas. Modifica primero el pedido.');const all=await new Parse.Query('OrderLine').equalTo('order',order).find({useMasterKey:true});requests.push(update(line,{received:qty}));requests.push(update(order,{status:all.every(l=>(l.id===line.id?qty:l.get('received'))>=l.get('quantity'))?'Recibido':all.some(l=>(l.id===line.id?qty:l.get('received'))>0)?'Parcial':'Pendiente'}));return{line,order};}
 Parse.Cloud.define('changeVaccineMovement',({user,params:p})=>serial(async()=>{
 await authorize(user);const professional=await profile(user);const old=await new Parse.Query('VaccineMovement').include('vaccineLot').include('receipt').get(p.id,{useMasterKey:true});const oldLot=old.get('vaccineLot');if(!oldLot)throw new Error('El lote original no está disponible.');const requests=[],deltas=new Map([[oldLot.id,{lot:oldLot,delta:Object.fromEntries(W.map(w=>[w,-effect(old)[w]]))}]]);
 let next,newLot,receipt=old.get('receipt');
 if(!p.delete){if(!integer(p.quantity)||p.quantity<1||!date(p.movementDate)||p.movementDate>new Date().toISOString().slice(0,10))throw new Error('Introduce fecha y unidades válidas.');newLot=p.lotId===oldLot.id?oldLot:await new Parse.Query('VaccineLot').get(p.lotId,{useMasterKey:true});const type=receipt?'in':old.get('type')==='initial'?'initial':p.type;if(!['initial','in','transfer','out','return','waste'].includes(type))throw new Error('Tipo de movimiento no válido.');
 const source=receipt?'Proveedor':type==='in'||type==='initial'?'':p.source,destination=receipt?'Nevera 2B':type==='out'?'Paciente':type==='return'?'Proveedor':type==='waste'?'Baja':p.destination;
 if(!['initial','in'].includes(type)&&!W.includes(source)||['initial','in','transfer'].includes(type)&&!W.includes(destination)||type==='transfer'&&source===destination)throw new Error('Revisa origen y destino.');
 if(type==='out'&&(!p.nhc?.trim()||! /^[A-Za-z0-9-]{1,40}$/.test(p.nhc.trim())))throw new Error('Introduce un NHC válido.');
 if(type==='out'&&newLot.get('expiry')<p.movementDate)throw new Error('El lote está caducado en la fecha del suministro.');if(type==='waste'&&!['Baja por rotura','Baja por caducidad'].includes(p.reason))throw new Error('Selecciona el motivo de la baja.');if(type==='waste'&&p.reason==='Baja por caducidad'&&newLot.get('expiry')>=p.movementDate)throw new Error('El lote no estaba caducado.');
 if(receipt&&newLot.get('code')!==receipt.get('code'))throw new Error('La vacuna recibida debe coincidir con la del pedido.');
 next={type,source,destination,quantity:p.quantity,movementDate:p.movementDate,nhc:type==='out'?p.nhc.trim():'',reason:receipt?'Recepción de pedido':type==='initial'?'Registro inicial':type==='in'?'Entrada manual de proveedor':type==='transfer'?'Transferencia':type==='return'?'Devolución por caducidad próxima':type==='out'?'Suministro a pacientes':p.reason,note:String(p.note||'').slice(0,300),vaccineLot:ptr(newLot),code:newLot.get('code'),sivac:newLot.get('sivac'),name:newLot.get('name'),lot:newLot.get('lot'),expiry:newLot.get('expiry'),modifiedBy:professional.get('nif')};
 const added=effect(next);const row=deltas.get(newLot.id)||{lot:newLot,delta:Object.fromEntries(W.map(w=>[w,0]))};for(const w of W)row.delta[w]+=added[w];deltas.set(newLot.id,row);
 }
 for(const{lot,delta}of deltas.values())requests.push(update(lot,{stocks:adjusted(lot,delta)}));
 if(receipt){const{order}=await adjustReceipt(receipt,p.delete?0:p.quantity,requests);if(!p.delete){if(p.movementDate<order.get('date')||newLot.get('expiry')<p.movementDate)throw new Error('Revisa fecha del pedido y caducidad del lote.');if(!p.deliveryNote?.trim())throw new Error('El número de albarán es obligatorio.');requests.push(update(receipt,{quantity:p.quantity,date:p.movementDate,deliveryNote:p.deliveryNote.trim().slice(0,60),lot:newLot.get('lot'),expiry:newLot.get('expiry'),vaccineLot:ptr(newLot),fingerprint:'modificado',modifiedBy:professional.get('nif')}));next.note=`Pedido ${order.get('number')} · Albarán ${p.deliveryNote.trim()}`;}else requests.push(remove(receipt));}
 requests.push(p.delete?remove(old):update(old,next));requests.push(audit(user,p.delete?'Eliminar movimiento':'Modificar movimiento',old));await commit(requests);return true;
 }));
 Parse.Cloud.define('lotEditingData',async({user,params:p})=>{await authorize(user);const lot=await new Parse.Query('VaccineLot').get(p.id,{useMasterKey:true});const rows=await new Parse.Query('VaccineMovement').equalTo('vaccineLot',lot).limit(10000).find({useMasterKey:true});const initial={...lot.get('stocks')};for(const m of rows)if(m.get('type')!=='initial'){const delta=effect(m);for(const w of W)initial[w]-=delta[w];}return {initialStocks:initial};});
 Parse.Cloud.define('editVaccineLot',({user,params:p})=>serial(async()=>{
 await authorize(user);const professional=await profile(user);for(const k of ['code','sivac','name','lot'])if(typeof p[k]!=='string'||!p[k].trim()||p[k].length>100)throw new Error('Completa los datos de vacuna y lote.');if(!date(p.expiry)||W.some(w=>!integer(p.initialStocks?.[w])||!integer(p.minimum?.[w])))throw new Error('Revisa caducidad, mínimos y unidades iniciales.');
 const lot=await new Parse.Query('VaccineLot').include('vaccine').get(p.id,{useMasterKey:true}),vaccine=lot.get('vaccine'),code=p.code.trim().toUpperCase();if(p.scanCode!==undefined&&p.scanCode!==null&&(typeof p.scanCode!=='string'||p.scanCode.trim().length>512||p.scanCode.includes('\u0000')))throw new Error('El código QR / barras no es válido o supera 512 caracteres.');const scanCode=String(p.scanCode===undefined?lot.get('scanCode')||'':p.scanCode||'').normalize('NFC').trim();if(!vaccine)throw new Error('La ficha de la vacuna no está disponible.');
 const [collision,duplicate,siblings,movements,receipts,lines]=await Promise.all([new Parse.Query('Vaccine').equalTo('code',code).notEqualTo('objectId',vaccine.id).first({useMasterKey:true}),new Parse.Query('VaccineLot').equalTo('code',code).equalTo('lot',p.lot.trim()).notEqualTo('objectId',lot.id).first({useMasterKey:true}),new Parse.Query('VaccineLot').equalTo('vaccine',vaccine).limit(10000).find({useMasterKey:true}),new Parse.Query('VaccineMovement').equalTo('code',vaccine.get('code')).limit(10000).find({useMasterKey:true}),new Parse.Query('OrderReceipt').equalTo('code',vaccine.get('code')).limit(10000).find({useMasterKey:true}),new Parse.Query('OrderLine').equalTo('vaccine',vaccine).limit(10000).find({useMasterKey:true})]);
 if(collision||duplicate)throw new Error('El código o lote ya pertenece a otro registro.');const relevant=movements.filter(m=>m.get('vaccineLot')?.id===lot.id);if(relevant.some(m=>m.get('type')==='out'&&(m.get('movementDate')||m.createdAt.toISOString().slice(0,10))>p.expiry))throw new Error('La caducidad no puede invalidar un suministro ya registrado.');
 const initial={...lot.get('stocks')};for(const m of relevant)if(m.get('type')!=='initial'){const d=effect(m);for(const w of W)initial[w]-=d[w];}const delta=Object.fromEntries(W.map(w=>[w,p.initialStocks[w]-initial[w]])),stocks=adjusted(lot,delta),identity={code,sivac:p.sivac.trim(),name:p.name.trim()},requests=[update(vaccine,{...identity,minimum:p.minimum})];
 for(const sibling of siblings)requests.push(update(sibling,sibling.id===lot.id?{...identity,lot:p.lot.trim(),expiry:p.expiry,scanCode,stocks}:identity));
 for(const m of movements){const same=m.get('vaccineLot')?.id===lot.id;if(same&&m.get('type')==='initial')requests.push(remove(m));else requests.push(update(m,same?{...identity,lot:p.lot.trim(),expiry:p.expiry}:identity));}
 for(const r of receipts)requests.push(update(r,r.get('vaccineLot')?.id===lot.id?{...identity,lot:p.lot.trim(),expiry:p.expiry,fingerprint:'modificado'}:identity));for(const line of lines)requests.push(update(line,identity));
 for(const w of W)if(p.initialStocks[w]>0)requests.push(create('VaccineMovement',{...identity,lot:p.lot.trim(),expiry:p.expiry,vaccineLot:ptr(lot),actor:ptr(user),professional:professional.get('nif'),movementDate:lot.createdAt.toISOString().slice(0,10),type:'initial',reason:'Registro inicial',source:'',destination:w,quantity:p.initialStocks[w],note:'Stock inicial corregido'}));requests.push(audit(user,'Modificar registro de vacuna',lot));await commit(requests);return true;
 }));
 async function revertReceipts(receipts,requests){const lineTotals=new Map(),orders=new Map();for(const r of receipts){const id=r.get('line').id;lineTotals.set(id,(lineTotals.get(id)||0)+r.get('quantity'));orders.set(r.get('order').id,r.get('order'));}const allLines=await Promise.all([...orders.values()].map(order=>new Parse.Query('OrderLine').equalTo('order',order).find({useMasterKey:true})));for(let i=0;i<allLines.length;i++){const lines=allLines[i],order=[...orders.values()][i];for(const line of lines)if(lineTotals.has(line.id)){const received=line.get('received')-lineTotals.get(line.id);if(received<0)throw new Error('El historial de recepciones no coincide con el pedido.');requests.push(update(line,{received}));}const amounts=lines.map(l=>l.get('received')-(lineTotals.get(l.id)||0));requests.push(update(order,{status:amounts.every((n,j)=>n>=lines[j].get('quantity'))?'Recibido':amounts.some(n=>n>0)?'Parcial':'Pendiente'}));}}
 Parse.Cloud.define('deleteVaccineLot',({user,params:p})=>serial(async()=>{
 await authorize(user);if(p.cascade!==true)throw new Error('Confirma la eliminación del lote y sus registros relacionados.');const lot=await new Parse.Query('VaccineLot').get(p.id,{useMasterKey:true});const[movements,receipts]=await Promise.all([new Parse.Query('VaccineMovement').equalTo('vaccineLot',lot).limit(10000).find({useMasterKey:true}),new Parse.Query('OrderReceipt').equalTo('vaccineLot',lot).limit(10000).find({useMasterKey:true})]);const requests=[];await revertReceipts(receipts,requests);requests.push(...movements.map(remove),...receipts.map(remove),remove(lot),audit(user,'Eliminar lote y registros relacionados',lot));const remaining=await new Parse.Query('VaccineLot').equalTo('vaccine',lot.get('vaccine')).notEqualTo('objectId',lot.id).count({useMasterKey:true});const lines=await new Parse.Query('OrderLine').equalTo('vaccine',lot.get('vaccine')).count({useMasterKey:true});if(!remaining&&!lines&&lot.get('vaccine'))requests.push(remove(lot.get('vaccine')));await commit(requests);return true;
 }));
 Parse.Cloud.define('editVaccineOrder',({user,params:p})=>serial(async()=>{
 await authorize(user);await profile(user);if(!date(p.date)||p.date>new Date().toISOString().slice(0,10)||!p.number?.trim()||!Array.isArray(p.lines)||!p.lines.length||new Set(p.lines.map(l=>l.code)).size!==p.lines.length||p.lines.some(l=>!integer(l.quantity)||l.quantity<1))throw new Error('Completa fecha, número y cantidades válidas.');const order=await new Parse.Query('VaccineOrder').get(p.id,{useMasterKey:true});const[oldLines,receipts,duplicate,vaccines]=await Promise.all([new Parse.Query('OrderLine').equalTo('order',order).find({useMasterKey:true}),new Parse.Query('OrderReceipt').equalTo('order',order).find({useMasterKey:true}),new Parse.Query('VaccineOrder').equalTo('number',p.number.trim()).notEqualTo('objectId',order.id).first({useMasterKey:true}),new Parse.Query('Vaccine').containedIn('code',p.lines.map(l=>l.code)).find({useMasterKey:true})]);if(duplicate||vaccines.length!==p.lines.length)throw new Error('Número duplicado o vacuna no disponible.');if(receipts.some(r=>r.get('date')<p.date))throw new Error('El pedido no puede ser posterior a una recepción registrada.');const byCode=new Map(oldLines.map(l=>[l.get('code'),l])),vByCode=new Map(vaccines.map(v=>[v.get('code'),v])),requests=[];
 for(const old of oldLines)if(!p.lines.some(l=>l.code===old.get('code'))){if(old.get('received')>0)throw new Error('Elimina primero las recepciones antes de retirar una vacuna del pedido.');requests.push(remove(old));}
 for(const l of p.lines){const old=byCode.get(l.code);if(old&&l.quantity<old.get('received'))throw new Error('Las unidades pedidas no pueden ser menores que las recibidas. Modifica primero las recepciones.');if(old)requests.push(update(old,{quantity:l.quantity}));else{const v=vByCode.get(l.code);requests.push(create('OrderLine',{order:ptr(order),vaccine:ptr(v),code:l.code,name:v.get('name'),sivac:v.get('sivac'),quantity:l.quantity,received:0}));}}
 const amounts=p.lines.map(l=>byCode.get(l.code)?.get('received')||0);requests.push(update(order,{date:p.date,number:p.number.trim(),status:amounts.every((n,i)=>n>=p.lines[i].quantity)?'Recibido':amounts.some(n=>n>0)?'Parcial':'Pendiente'}));for(const r of receipts)requests.push(update(r,{orderNumber:p.number.trim()}));const receiptById=new Map(receipts.map(r=>[r.id,r]));const movements=await new Parse.Query('VaccineMovement').equalTo('order',order).find({useMasterKey:true});for(const m of movements){const receipt=receiptById.get(m.get('receipt')?.id);if(receipt)requests.push(update(m,{note:`Pedido ${p.number.trim()} · Albarán ${receipt.get('deliveryNote')}`}));}requests.push(audit(user,'Modificar pedido',order));await commit(requests);return true;
 }));
 Parse.Cloud.define('deleteVaccineOrder',({user,params:p})=>serial(async()=>{
 await authorize(user);if(p.cascade!==true)throw new Error('Confirma la eliminación del pedido y sus recepciones.');const order=await new Parse.Query('VaccineOrder').get(p.id,{useMasterKey:true});const[lines,receipts,movements]=await Promise.all([new Parse.Query('OrderLine').equalTo('order',order).find({useMasterKey:true}),new Parse.Query('OrderReceipt').equalTo('order',order).include('vaccineLot').find({useMasterKey:true}),new Parse.Query('VaccineMovement').equalTo('order',order).find({useMasterKey:true})]);const deltas=new Map();for(const r of receipts){const lot=r.get('vaccineLot');if(!lot)throw new Error('No está disponible un lote recibido.');const row=deltas.get(lot.id)||{lot,delta:{'Nevera 2B':0}};row.delta['Nevera 2B']-=r.get('quantity');deltas.set(lot.id,row);}const requests=[...deltas.values()].map(({lot,delta})=>update(lot,{stocks:adjusted(lot,delta)}));requests.push(...movements.map(remove),...receipts.map(remove),...lines.map(remove),remove(order),audit(user,'Eliminar pedido y recepciones',order));await commit(requests);return true;
 }));
}
