import {useEffect,useId,useRef,useState} from 'react';
import {Camera,X,ShieldCheck} from 'lucide-react';
import type {Html5Qrcode} from 'html5-qrcode';
type Device={id:string;label:string};
async function dispose(reader:Html5Qrcode|null){if(!reader)return;try{if(reader.isScanning)await reader.stop();}catch{}try{reader.clear();}catch{}}
function explain(error:unknown){const text=String(error);if(/NotAllowed|Permission|denied|permission/i.test(text))return 'Permite el acceso a la cámara en tu navegador. Si la vista previa lo bloquea, abre la aplicación en su propia pestaña.';if(/NotFound|DevicesNotFound|no cameras/i.test(text))return 'No se encontró una cámara. Puedes introducir el código manualmente.';if(/NotReadable|TrackStart|in use/i.test(text))return 'La cámara está ocupada por otra aplicación. Ciérrala y vuelve a intentarlo.';return 'No se pudo activar la cámara. Comprueba sus permisos y que estás usando HTTPS. Puedes continuar manualmente.';}
export default function CameraScanner({onDetected,onClose}:{onDetected:(code:string)=>void;onClose:()=>void}){
 const id='vaccine-reader-'+useId().replace(/:/g,''),reader=useRef<Html5Qrcode|null>(null),task=useRef<Promise<void>>(Promise.resolve()),alive=useRef(true),detected=useRef(false),close=useRef(onClose);close.current=onClose;
 const[busy,setBusy]=useState(false),[active,setActive]=useState(false),[error,setError]=useState(''),[devices,setDevices]=useState<Device[]>([]),[deviceId,setDeviceId]=useState('');
 useEffect(()=>{alive.current=true;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')close.current();};window.addEventListener('keydown',escape);return()=>{alive.current=false;window.removeEventListener('keydown',escape);task.current.then(()=>dispose(reader.current)).catch(()=>{});};},[]);
 function start(){if(busy||active)return;setBusy(true);setError('');detected.current=false;task.current=(async()=>{try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('HTTPS or camera unavailable');const {Html5Qrcode,Html5QrcodeSupportedFormats:F}=await import('html5-qrcode');if(!alive.current)return;await dispose(reader.current);const cameras=devices.length?devices:await Html5Qrcode.getCameras();if(!alive.current)return;if(!cameras.length)throw new Error('no cameras');setDevices(cameras);const chosen=deviceId||cameras.find(c=>/back|rear|trasera|environment/i.test(c.label))?.id||cameras[0].id;setDeviceId(chosen);const scanner=new Html5Qrcode(id,{verbose:false,formatsToSupport:[F.QR_CODE,F.DATA_MATRIX,F.CODE_128,F.CODE_39,F.CODE_93,F.EAN_13,F.EAN_8,F.UPC_A,F.UPC_E,F.ITF,F.CODABAR,F.AZTEC,F.PDF_417]});reader.current=scanner;await scanner.start(chosen,{fps:10,aspectRatio:1.333},text=>{if(detected.current||!alive.current)return;detected.current=true;dispose(scanner).then(()=>{if(alive.current)onDetected(text);});},()=>{});if(!alive.current){await dispose(scanner);return;}if(!detected.current)setActive(true);}catch(e){await dispose(reader.current);if(alive.current){setActive(false);setError(explain(e));}}finally{if(alive.current)setBusy(false);}})();}
 async function stop(){setBusy(true);await dispose(reader.current);if(alive.current){setActive(false);setBusy(false);}}
 return <div className="overlay scanner-overlay"><section className="modal scanner-modal" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><div className="section-heading"><div><span className="eyebrow">LECTURA OPCIONAL</span><h2 id="scanner-title">Escanear QR / código de barras</h2></div><button className="icon-button" type="button" aria-label="Cerrar escáner y apagar cámara" onClick={onClose}><X size={20}/></button></div><p className="form-hint">Enfoca el código con buena luz y sin reflejos.</p><div id={id} className="scanner-reader"/>{!active&&!busy&&<div className="scanner-intro"><Camera size={32}/><p>Activa la cámara para empezar. El navegador solicitará tu permiso.</p></div>}{devices.length>1&&<label>Cámara<select value={deviceId} disabled={busy||active} onChange={e=>setDeviceId(e.target.value)}>{devices.map((c,i)=><option key={c.id} value={c.id}>{c.label||`Cámara ${i+1}`}</option>)}</select></label>}{error&&<p className="error" role="alert">{error}</p>}<div className="scanner-status" role="status">{busy?'Preparando cámara…':active?'Cámara activa. Buscando un código…':'Cámara apagada.'}</div><button type="button" className="primary wide" disabled={busy} onClick={active?stop:start}><Camera size={17}/>{busy?'Espera…':active?'Apagar cámara':'Activar cámara'}</button><p className="scanner-privacy"><ShieldCheck size={16}/> La imagen se procesa en tu navegador; no se suben fotos ni vídeos. Escanear no guarda movimientos.</p><button className="text-button" type="button" onClick={onClose}>Cerrar y continuar manualmente</button></section></div>;
}
