import {useEffect,useState} from 'react';
import {X} from 'lucide-react';
import Parse from '../parse';
import {WAREHOUSES,type Movement,type VaccineLot} from '../hooks/useInventory';
import ScanLotButton from './ScanLotButton';
import {localToday} from '../lib/inventory';
export default function EditMovementForm({movement,lots,onClose,onSaved}:{movement:Movement;lots:VaccineLot[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const[type,setType]=useState(movement.type),[lotId,setLotId]=useState(movement.vaccineLotId||lots.find(l=>l.code===movement.code&&l.lot===movement.lot)?.id||''),[source,setSource]=useState(movement.source),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deliveryNote,setDeliveryNote]=useState(''),[loadingReceipt,setLoadingReceipt]=useState(!!movement.receiptId);const receipt=!!movement.receiptId,initial=movement.type==='initial',selected=lots.find(l=>l.id===lotId),available=receipt?lots.filter(l=>l.code===movement.code):lots;
 useEffect(()=>{if(!movement.receiptId)return;new Parse.Query('OrderReceipt').get(movement.receiptId).then(r=>setDeliveryNote(r.get('deliveryNote'))).catch(()=>setError('No se pudo cargar el albarán.')).finally(()=>setLoadingReceipt(false));},[movement.receiptId]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await Parse.Cloud.run('changeVaccineMovement',{id:movement.id,lotId,type,source,destination:receipt?'Nevera 2B':d.get('destination'),quantity:Number(d.get('quantity')),movementDate:d.get('date'),nhc:d.get('nhc'),reason:d.get('reason'),note:d.get('note'),deliveryNote});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="overlay"><section className="modal vaccine-modal" role="dialog" aria-modal="true" aria-labelledby="edit-movement-title"><div className="section-heading"><h2 id="edit-movement-title">Modificar {receipt?'recepción':'movimiento'}</h2><button className="icon-button" aria-label="Cerrar" onClick={onClose} disabled={busy}><X size={20}/></button></div><form onSubmit={save}><p className="form-hint">Se deshará el efecto anterior y se aplicarán estos datos, conservando el resto del historial.</p><label>Fecha<input name="date" type="date" defaultValue={movement.movementDate||new Date(movement.createdAt).toLocaleDateString('sv-SE')} max={localToday()} required/></label><ScanLotButton lots={available} disabled={busy} onClear={()=>setLotId('')} onSelect={lot=>setLotId(lot.id)}/><label>Vacuna y lote<select value={lotId} onChange={e=>setLotId(e.target.value)} required><option value="">Selecciona un lote</option>{available.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name} · Lote {l.lot}</option>)}</select></label><div className="form-row"><label>Código vacuna<input readOnly value={selected?.code||''}/></label><label>Caducidad<input readOnly type="date" value={selected?.expiry||''}/></label></div><label>Tipo<select value={type} disabled={receipt||initial} onChange={e=>setType(e.target.value)}>{initial?<option value="initial">Registro inicial</option>:<><option value="transfer">TRANSFERENCIA</option><option value="out">SALIDA · Paciente</option><option value="return">DEVOLUCIÓN · Proveedor</option><option value="waste">BAJA</option><option value="in">ENTRADA</option></>}</select></label>{!receipt&&!['initial','in'].includes(type)&&<label>Origen<select value={source} onChange={e=>setSource(e.target.value)} required>{WAREHOUSES.map(w=><option key={w}>{w}</option>)}</select></label>}{!receipt&&['initial','in','transfer'].includes(type)&&<label>Destino<select name="destination" required defaultValue={movement.destination}>{WAREHOUSES.map(w=><option key={w}>{w}</option>)}</select></label>}{receipt&&<><label>Número de albarán<input value={deliveryNote} onChange={e=>setDeliveryNote(e.target.value)} required maxLength={60}/></label><label>Destino<input readOnly value="Nevera 2B"/></label></>}{type==='out'&&<label>NHC<input name="nhc" defaultValue={movement.nhc||''} required pattern="[A-Za-z0-9-]+" maxLength={40}/></label>}{type==='waste'&&<label>Motivo<select name="reason" defaultValue={movement.reason}><option value="Baja por rotura">Rotura</option><option value="Baja por caducidad">Caducada</option></select></label>}<label>Unidades<input name="quantity" type="number" min="1" max="1000000" step="1" required defaultValue={movement.quantity}/></label>{!receipt&&<label>Nota<input name="note" maxLength={300} defaultValue={movement.note}/></label>}{error&&<p className="error">{error}</p>}<button className="primary wide" disabled={busy||loadingReceipt||!selected}>{busy?'Guardando…':'Guardar y actualizar stock'}</button></form></section></div>;
}
