import {useCallback,useEffect,useRef,useState} from 'react';
import {Ticket,Copy,Plus,RefreshCw} from 'lucide-react';
import Parse from '../parse';
type Invitation={id:string;label:string;createdAt:string;expiresAt:string;usedAt:string;email:string;status:string};
type Professional={id:string;email:string;nif:string;authorized:boolean;admin:boolean};
type Generated={id:string;code:string;expiresAt:string};
export default function InvitationManager(){
 const[rows,setRows]=useState<Invitation[]>([]),[people,setPeople]=useState<Professional[]>([]),[generated,setGenerated]=useState<Generated|null>(null),[label,setLabel]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(''),[confirm,setConfirm]=useState<{id:string;type:'invitation'|'user';label:string}|null>(null);const codeInput=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{try{const[inv,p]=await Promise.all([Parse.Cloud.run('listInvitations'),Parse.Cloud.run('listProfessionals')]);setRows(inv);setPeople(p.filter((person:Professional)=>person.authorized));setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{refresh();},[refresh]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setCopied('');try{setGenerated(await Parse.Cloud.run('createInvitation',{label}));setLabel('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function copy(){if(!generated)return;try{await navigator.clipboard.writeText(generated.code);setCopied('Código copiado. Compártelo de forma privada con la persona invitada.');}catch{codeInput.current?.focus();codeInput.current?.select();setCopied('Código seleccionado. Cópialo manualmente y compártelo de forma privada.');}}
 async function remove(){if(!confirm)return;setBusy(true);setError('');try{await Parse.Cloud.run(confirm.type==='invitation'?'cancelInvitation':'revokeInvitedUser',{id:confirm.id});if(generated?.id===confirm.id)setGenerated(null);setConfirm(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="panel invitation-create"><div className="section-heading"><div><h2><Ticket size={20}/> Invitar a una persona</h2><p className="subtext">Un código. Una cuenta. Sin aprobación manual.</p></div><button className="icon-button" aria-label="Actualizar invitaciones" disabled={busy} onClick={refresh}><RefreshCw size={17}/></button></div><form className="invitation-form" onSubmit={create}><label>Referencia de la invitación (opcional)<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={100} placeholder="Por ejemplo: incorporación del equipo"/></label><button className="primary" disabled={busy}><Plus size={17}/>{busy?'Espera…':'Generar código'}</button></form><p className="form-hint">Cada código caduca en 7 días y solo permite activar una cuenta. La persona crea o inicia su sesión, introduce el código y su NIF/NIE y entra directamente. El código no se envía por correo automáticamente.</p>{generated&&<div className="invitation-code-box"><label>Código generado<input ref={codeInput} value={generated.code} readOnly aria-label="Código generado para compartir"/></label><button className="secondary" onClick={copy}><Copy size={16}/> Copiar código</button><p>Válido hasta {new Date(generated.expiresAt).toLocaleString('es-ES')}. Se muestra solo ahora: cópialo antes de salir de esta sección. Si lo pierdes, anúlalo y genera otro.</p>{copied&&<p role="status">{copied}</p>}</div>}{error&&<p className="error" role="alert">{error}</p>}</section>
 <section className="panel activity"><div className="section-heading"><h2>Códigos de invitación</h2><span className="eyebrow">ÚLTIMOS 500</span></div>{!rows.length?<p className="empty">Todavía no hay invitaciones. Genera tu primer código arriba.</p>:<div className="table-wrap"><table><thead><tr><th>REFERENCIA</th><th>CREADO</th><th>CADUCIDAD DEL CÓDIGO</th><th>ESTADO</th><th>CUENTA QUE LO USÓ</th><th>ACCIÓN</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.label||'Sin referencia'}</td><td>{new Date(r.createdAt).toLocaleDateString('es-ES')}</td><td>{new Date(r.expiresAt).toLocaleString('es-ES')}</td><td><span className={`stock-badge ${r.status==='Utilizado'?'healthy':r.status==='Disponible'?'':'low'}`}>{r.status}</span></td><td>{r.email||'—'}</td><td>{r.status==='Disponible'&&<button className="secondary" disabled={busy} onClick={()=>setConfirm({id:r.id,type:'invitation',label:r.label||'este código'})}>Anular código</button>}</td></tr>)}</tbody></table></div>}</section>
 <section className="panel activity"><div className="section-heading"><h2>Personas con acceso</h2></div><p className="form-hint access-description">No hay solicitudes pendientes ni botones de autorización. Los códigos activan el acceso automáticamente. La caducidad del código no expulsa a quien ya lo utilizó.</p><div className="table-wrap"><table><thead><tr><th>CUENTA</th><th>NIF / NIE</th><th>TIPO</th><th>ACCIÓN</th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td>{p.email}</td><td>{p.nif}</td><td>{p.admin?'Administración':'Usuario'}</td><td>{!p.admin&&<button className="secondary" disabled={busy} onClick={()=>setConfirm({id:p.id,type:'user',label:p.email})}>Retirar acceso</button>}</td></tr>)}</tbody></table></div></section>
 {confirm&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="invitation-confirm-title"><h2 id="invitation-confirm-title">{confirm.type==='invitation'?'Anular invitación':'Retirar acceso'}</h2><p className="delete-description">{confirm.type==='invitation'?`El código de ${confirm.label} dejará de permitir la entrada. Puedes generar otro cuando quieras.`:`${confirm.label} ya no podrá consultar ni registrar datos. Sus vacunas y movimientos no se borrarán; necesitará una nueva invitación para volver a entrar.`}</p>{error&&<p className="error">{error}</p>}<div className="table-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancelar</button><button className="danger-button" disabled={busy} onClick={remove}>{busy?'Guardando…':'Confirmar'}</button></div></section></div>}</>;
}
