import {useState} from 'react';
import {X,Trash2,Plus} from 'lucide-react';
import Parse from '../parse';
import type {Vaccine} from '../hooks/useInventory';
import type {VaccineOrder,OrderLine} from '../lib/orderTypes';
import {localToday} from '../lib/inventory';
export default function OrderForm({vaccines,suggestions,onClose,onSaved,order,orderLines}:{vaccines:Vaccine[];suggestions:{code:string;quantity:number}[];onClose:()=>void;onSaved:()=>Promise<void>;order?:VaccineOrder;orderLines?:OrderLine[]}){
 const[lines,setLines]=useState(()=>orderLines?.length?orderLines.map(l=>({code:l.code,quantity:l.quantity})):suggestions.length?suggestions:[{code:vaccines[0]?.code||'',quantity:1}]),[busy,setBusy]=useState(false),[error,setError]=useState('');const byCode=new Map(vaccines.map(v=>[v.code,v]));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!lines.length){setError('Añade al menos una vacuna.');return;}const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await Parse.Cloud.run(order?'editVaccineOrder':'createVaccineOrder',{id:order?.id,date:d.get('date'),number:d.get('number'),lines});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="overlay"><section className="modal vaccine-modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><div className="section-heading"><h2 id="order-title">{order?'Modificar pedido':'Nuevo pedido a proveedor'}</h2><button className="icon-button" aria-label="Cerrar" disabled={busy} onClick={onClose}><X size={20}/></button></div><form onSubmit={submit}><div className="form-row"><label>Fecha<input name="date" type="date" defaultValue={order?.date||localToday()} max={localToday()} required/></label><label>Número de pedido<input name="number" defaultValue={order?.number||''} required maxLength={60} autoFocus/></label></div><p className="form-hint">{order?'El pedido no modifica el stock por sí mismo. Las cantidades no pueden ser inferiores a las ya recibidas; corrige sus recepciones para modificar el stock.':'Propuesta para alcanzar el mínimo de Nevera 2B, descontando lo ya pedido. Revisa y confirma las cantidades.'}</p>{lines.map((l,i)=><div className="order-line-editor" key={i}><label>Vacuna<select value={l.code} onChange={e=>setLines(prev=>prev.map((row,j)=>j===i?{...row,code:e.target.value}:row))}>{vaccines.map(v=><option key={v.id} value={v.code}>{v.code} · {v.name}</option>)}</select><small>SIVAC: {byCode.get(l.code)?.sivac}</small></label><label>Unidades<input type="number" required min="1" max="1000000" step="1" value={l.quantity} onChange={e=>setLines(prev=>prev.map((row,j)=>j===i?{...row,quantity:Number(e.target.value)}:row))}/></label><button type="button" className="icon-button" aria-label="Quitar vacuna" onClick={()=>setLines(prev=>prev.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>)}<button type="button" className="secondary" onClick={()=>setLines(prev=>[...prev,{code:vaccines.find(v=>!prev.some(l=>l.code===v.code))?.code||vaccines[0].code,quantity:1}])}><Plus size={15}/> Añadir vacuna</button>{error&&<p className="error">{error}</p>}<button className="primary wide order-submit" disabled={busy}>{busy?'Guardando…':order?'Guardar pedido':'Confirmar pedido'}</button></form></section></div>;
}
