import {lazy,Suspense,useState} from 'react';
import {Plus,PackageCheck,Pencil,Trash2} from 'lucide-react';
import type {Vaccine,VaccineLot,Movement} from '../hooks/useInventory';
import type {VaccineOrder,OrderLine,OrderReceipt} from '../lib/orderTypes';
import Parse from '../parse';
import {balancesByCode,formatDate} from '../lib/inventory';
const OrderForm=lazy(()=>import('./OrderForm'));
const ReceiptForm=lazy(()=>import('./ReceiptForm'));
const EditMovementForm=lazy(()=>import('./EditMovementForm'));
const DeleteRecordDialog=lazy(()=>import('./DeleteRecordDialog'));
export default function Orders({vaccines,lots,orders,lines,receipts,movements,nif,onSaved}:{vaccines:Vaccine[];lots:VaccineLot[];orders:VaccineOrder[];lines:OrderLine[];receipts:OrderReceipt[];movements:Movement[];nif:string;onSaved:()=>Promise<void>}){
 const[newOrder,setNewOrder]=useState(false),[receive,setReceive]=useState<VaccineOrder|null>(null),[selected,setSelected]=useState(''),[editOrder,setEditOrder]=useState<VaccineOrder|null>(null),[deleteOrder,setDeleteOrder]=useState<VaccineOrder|null>(null),[editReceipt,setEditReceipt]=useState<Movement|null>(null),[deleteReceipt,setDeleteReceipt]=useState<Movement|null>(null),[receiptBusy,setReceiptBusy]=useState(false),[actionError,setActionError]=useState('');const balances=balancesByCode(lots),orderById=new Map(orders.map(o=>[o.id,o])),movementByReceipt=new Map(movements.filter(m=>m.receiptId).map(m=>[m.receiptId,m]));const pending=new Map<string,number>();for(const l of lines)if(orderById.get(l.orderId)?.status!=='Recibido')pending.set(l.code,(pending.get(l.code)||0)+Math.max(0,l.quantity-l.received));
 const suggestions=vaccines.map(v=>({code:v.code,quantity:Math.max(0,v.minimum['Nevera 2B']-(balances.get(v.code)?.['Nevera 2B']||0)-(pending.get(v.code)||0))})).filter(l=>l.quantity>0);const shownLines=selected?lines.filter(l=>l.orderId===selected):[],shownReceipts=selected?receipts.filter(r=>r.orderId===selected):receipts;
 async function openReceipt(r:OrderReceipt,edit:boolean){const cached=movementByReceipt.get(r.id);if(cached){if(edit)setEditReceipt(cached);else setDeleteReceipt(cached);return;}setReceiptBusy(true);setActionError('');try{const receipt=new Parse.Object('OrderReceipt');receipt.id=r.id;const found=await new Parse.Query('VaccineMovement').equalTo('receipt',receipt).first();if(!found)throw new Error('No se encontró el movimiento de esta recepción.');const m={id:found.id!,...found.attributes,vaccineLotId:found.get('vaccineLot')?.id,receiptId:r.id} as Movement;if(edit)setEditReceipt(m);else setDeleteReceipt(m);}catch(e){setActionError((e as Error).message);}finally{setReceiptBusy(false);}}
 return <>{actionError&&<p className="error">{actionError}</p>}<section className="panel"><div className="section-heading report-heading"><div><h2>Pedidos a proveedor</h2><p className="subtext">Reposición de Nevera 2B · Confirmación manual</p></div><button className="primary" disabled={!vaccines.length} onClick={()=>setNewOrder(true)}><Plus size={17}/> Nuevo pedido</button></div><p className="access-description form-hint">{suggestions.length} vacunas necesitan pedido, descontando unidades ya pendientes. Los pedidos se registran aquí; no se envían al proveedor.</p>{!orders.length?<p className="empty">No hay pedidos registrados. Crea uno con la propuesta de reposición.</p>:<div className="table-wrap"><table><thead><tr><th>FECHA</th><th>NÚMERO DE PEDIDO</th><th>PROFESIONAL</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{formatDate(o.date)}</td><td><strong>{o.number}</strong></td><td>{o.professional}</td><td><span className={`stock-badge ${o.status==='Recibido'?'healthy':'low'}`}>{o.status}</span></td><td><div className="table-actions"><button className="secondary" onClick={()=>setSelected(p=>p===o.id?'':o.id)}>{selected===o.id?'Ocultar detalle':'Ver vacunas'}</button>{o.status!=='Recibido'&&<button className="secondary" onClick={()=>setReceive(o)}><PackageCheck size={15}/> Recibir</button>}<button className="icon-button" aria-label={`Modificar pedido ${o.number}`} title="Modificar" onClick={()=>setEditOrder(o)}><Pencil size={16}/></button><button className="icon-button delete-icon" aria-label={`Eliminar pedido ${o.number}`} title="Eliminar" onClick={()=>setDeleteOrder(o)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}</section>
 {selected&&orderById.has(selected)&&<section className="panel activity"><div className="section-heading report-heading"><h2>Vacunas del pedido {orderById.get(selected)?.number}</h2></div><div className="table-wrap"><table><thead><tr><th>CÓDIGO VACUNA</th><th>CÓDIGO SIVAC</th><th>VACUNA</th><th>PEDIDAS</th><th>RECIBIDAS</th><th>PENDIENTES</th></tr></thead><tbody>{shownLines.map(l=><tr key={l.id}><td>{l.code}</td><td>{l.sivac}</td><td>{l.name}</td><td>{l.quantity}</td><td>{l.received}</td><td>{l.quantity-l.received}</td></tr>)}</tbody></table></div></section>}
 <section className="panel activity"><div className="section-heading report-heading"><h2>Recepciones {selected?'del pedido seleccionado':''}</h2><span className="eyebrow">DESTINO: NEVERA 2B</span></div>{!shownReceipts.length?<p className="empty">Las recepciones registradas aparecerán aquí.</p>:<div className="table-wrap"><table><thead><tr><th>FECHA</th><th>PEDIDO</th><th>ALBARÁN</th><th>CÓDIGO / SIVAC</th><th>VACUNA / LOTE</th><th>CADUCIDAD</th><th>UNIDADES</th><th>NEVERA</th><th>PROFESIONAL</th><th>ACCIONES</th></tr></thead><tbody>{shownReceipts.map(r=>{return <tr key={r.id}><td>{formatDate(r.date)}</td><td>{r.orderNumber}</td><td>{r.deliveryNote}</td><td>{r.code}<small className="cell-small">{r.sivac}</small></td><td><strong>{r.name}</strong><small className="cell-small">{r.lot}</small></td><td>{formatDate(r.expiry)}</td><td>{r.quantity}</td><td>{r.warehouse}</td><td>{r.professional}</td><td><div className="table-actions"><button className="icon-button" disabled={receiptBusy} aria-label={`Modificar recepción ${r.deliveryNote}`} title="Modificar" onClick={()=>openReceipt(r,true)}><Pencil size={16}/></button><button className="icon-button delete-icon" disabled={receiptBusy} aria-label={`Eliminar recepción ${r.deliveryNote}`} title="Eliminar" onClick={()=>openReceipt(r,false)}><Trash2 size={16}/></button></div></td></tr>;})}</tbody></table></div>}</section>
 {newOrder&&<Suspense fallback={null}><OrderForm vaccines={vaccines} suggestions={suggestions} onClose={()=>setNewOrder(false)} onSaved={onSaved}/></Suspense>}{editOrder&&<Suspense fallback={null}><OrderForm vaccines={vaccines} suggestions={[]} order={editOrder} orderLines={lines.filter(l=>l.orderId===editOrder.id)} onClose={()=>setEditOrder(null)} onSaved={onSaved}/></Suspense>}{receive&&<Suspense fallback={null}><ReceiptForm order={receive} lots={lots} lines={lines.filter(l=>l.orderId===receive.id&&l.received<l.quantity)} nif={nif} onClose={()=>setReceive(null)} onSaved={onSaved}/></Suspense>}{editReceipt&&<Suspense fallback={null}><EditMovementForm movement={editReceipt} lots={lots} onSaved={onSaved} onClose={()=>setEditReceipt(null)}/></Suspense>}{deleteReceipt&&<Suspense fallback={null}><DeleteRecordDialog title="Eliminar recepción" description="Se descontarán las unidades recibidas del stock de Nevera 2B, se eliminará su movimiento y el pedido volverá a tener esas unidades pendientes. No se permite dejar stock negativo." fn="changeVaccineMovement" params={{id:deleteReceipt.id,delete:true}} onSaved={onSaved} onClose={()=>setDeleteReceipt(null)}/></Suspense>}{deleteOrder&&<Suspense fallback={null}><DeleteRecordDialog title={`Eliminar pedido ${deleteOrder.number}`} description="Se eliminará el pedido, sus líneas, todas sus recepciones y sus movimientos vinculados. Se descontarán del stock las unidades recibidas. Si ya se han usado y no queda stock suficiente, la eliminación se bloqueará." fn="deleteVaccineOrder" params={{id:deleteOrder.id,cascade:true}} onSaved={onSaved} onClose={()=>setDeleteOrder(null)}/></Suspense>}</>;
}
