import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Printer,FileSpreadsheet} from 'lucide-react';
export default function PrintControls({title,filters,count,notice,disabled=false}:{title:string;filters:string[];count:number;notice?:string;disabled?:boolean}){
 const[printedAt,setPrintedAt]=useState(''),[error,setError]=useState('');const previousTitle=useRef<string|null>(null);
 useEffect(()=>{const restore=()=>{if(previousTitle.current!==null){document.title=previousTitle.current;previousTitle.current=null;}};window.addEventListener('afterprint',restore);return()=>{window.removeEventListener('afterprint',restore);restore();};},[]);
 function exportSheet(e:React.MouseEvent<HTMLButtonElement>){const region=e.currentTarget.closest('.print-region');if(!region)return;const rows=Array.from(region.querySelectorAll('table tr')).map(row=>Array.from(row.querySelectorAll('th,td')).filter(cell=>!cell.classList.contains('no-print')&&!cell.querySelector('button')).map(cell=>{let value=(cell.textContent||'').trim();if(/^[=+@-]/.test(value))value="'"+value;return '"'+value.replace(/"/g,'""')+'"';}).join(';'));const blob=new Blob(['\uFEFF'+rows.join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=title+'-'+new Date().toISOString().slice(0,10)+'.csv';link.click();URL.revokeObjectURL(url);}
 function print(){setError('');flushSync(()=>setPrintedAt(new Date().toLocaleString('es-ES')));if(previousTitle.current===null)previousTitle.current=document.title;document.title=`Gestión de STOCK VACUNAS - ${title} - ${new Date().toLocaleDateString('sv-SE')}`;try{window.print();}catch{document.title=previousTitle.current||'Gestión de STOCK VACUNAS';previousTitle.current=null;setError('No se pudo abrir la impresión. Abre la aplicación en su propia pestaña y vuelve a intentarlo.');}}
 return <><div className="print-controls no-print"><button className="secondary" disabled={disabled} onClick={print}><Printer size={17}/> Imprimir / Guardar PDF</button><button className="secondary" disabled={disabled||count===0} onClick={exportSheet}><FileSpreadsheet size={17}/> Exportar hoja de cálculo (CSV)</button><span>Se imprimen los datos con los filtros actuales.</span></div>{error&&<p className="error no-print" role="alert">{error}</p>}<header className="print-only print-document-heading"><div className="print-document-top"><strong>Gestión de STOCK VACUNAS.</strong><span>Generado: {printedAt}</span></div><h1>{title}</h1><p>{filters.filter(Boolean).join(' · ')||'Sin filtros'}</p><p>{count.toLocaleString('es-ES')} registros{notice?` · ${notice}`:''}</p><small>Documento de uso interno. Protege los datos personales que pueda contener.</small></header></>;
}
