import {useState} from 'react';
import {X} from 'lucide-react';
import Parse from '../parse';
import type {VaccineOrder,OrderLine} from '../lib/orderTypes';
import type {VaccineLot} from '../hooks/useInventory';
import ScanLotButton from './ScanLotButton';
import {localToday} from '../lib/inventory';
export default function ReceiptForm({order,lines,lots,nif,onClose,onSaved}:{order:VaccineOrder;lines:OrderLine[];lots:VaccineLot[];nif:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const[lineId,setLineId]=useState(lines[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[operationId]=useState(()=>crypto.randomUUID()),[lotText,setLotText]=useState(''),[expiryText,setExpiryText]=useState('');const selected=lines.find(l=>l.id===lineId);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await Parse.Cloud.run('receiveVaccineOrder',{operationId,lineId,date:d.get('date'),deliveryNote:d.get('deliveryNote'),lot:d.get('lot'),expiry:d.get('expiry'),quantity:Number(d.get('quantity'))});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="overlay"><section className="modal vaccine-modal" role="dialog" aria-modal="true" aria-labelledby="receipt-title"><div className="section-heading"><h2 id="receipt-title">Recepción del pedido {order.number}</h2><button className="icon-button" aria-label="Cerrar" onClick={onClose} disabled={busy}><X size={20}/></button></div><form onSubmit={submit}><div className="form-row"><label>Fecha<input name="date" type="date" required min={order.date} max={localToday()} defaultValue={localToday()}/></label><label>Número de albarán<input name="deliveryNote" required maxLength={60} autoFocus/></label></div><label>Vacuna del pedido<select value={lineId} onChange={e=>setLineId(e.target.value)} required>{lines.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name} · {l.quantity-l.received} pendientes</option>)}</select></label><div className="form-row"><label>Código vacuna<input value={selected?.code||''} readOnly/></label><label>Código SIVAC<input value={selected?.sivac||''} readOnly/></label></div><ScanLotButton lots={lots.filter(l=>lines.some(line=>line.code===l.code))} disabled={busy} onClear={()=>{setLotText('');setExpiryText('');}} onSelect={lot=>{const line=lines.find(l=>l.code===lot.code);if(line)setLineId(line.id);setLotText(lot.lot);setExpiryText(lot.expiry);}}/><div className="form-row"><label>Lote recibido<input name="lot" required maxLength={100} value={lotText} onChange={e=>setLotText(e.target.value)}/></label><label>Caducidad<input name="expiry" type="date" required min={localToday()} value={expiryText} onChange={e=>setExpiryText(e.target.value)}/></label></div><label>Unidades recibidas de este lote<input name="quantity" type="number" min="1" max={selected?(selected.quantity-selected.received):0} step="1" required/></label><div className="form-row"><label>Nevera<input readOnly value="Nevera 2B"/></label><label>Profesional (NIF)<input readOnly value={nif}/></label></div><p className="form-hint">Se sumarán automáticamente a Nevera 2B. Para varios lotes o entregas parciales, registra una recepción por lote. El pedido seguirá pendiente hasta recibir todas sus unidades.</p>{error&&<p className="error">{error}</p>}<button className="primary wide" disabled={busy||!selected}>{busy?'Guardando…':'Registrar recepción'}</button></form></section></div>;
}
