import {useState} from 'react';
import {WAREHOUSES,type Vaccine,type VaccineLot,type Movement} from '../hooks/useInventory';
import {balancesByCode,formatDate,localToday} from '../lib/inventory';
import PrintControls from './PrintControls';
import MovementHistory from './MovementHistory';
import type {VaccineOrder,OrderLine} from '../lib/orderTypes';
const REPORTS=['Reposición','Consumo','Historial de movimientos','Caducadas','Pedidos a proveedor'];
export default function Reports({vaccines,lots,movements,orders,orderLines,onSaved}:{vaccines:Vaccine[];lots:VaccineLot[];movements:Movement[];orders:VaccineOrder[];orderLines:OrderLine[];onSaved:()=>Promise<void>}){
 const[report,setReport]=useState('Reposición'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[code,setCode]=useState(''),[warehouse,setWarehouse]=useState('Todos'),[nhc,setNhc]=useState(''),[professional,setProfessional]=useState('');const balances=balancesByCode(lots);
 const inRange=(date:string)=>(!from||date>=from)&&(!to||date<=to);
 const replenish=vaccines.filter(v=>!code||v.code===code).flatMap(v=>WAREHOUSES.filter(w=>(warehouse==='Todos'||warehouse===w)&&(balances.get(v.code)?.[w]||0)<v.minimum[w]).map(w=>({v,w,stock:balances.get(v.code)?.[w]||0,units:v.minimum[w]-(balances.get(v.code)?.[w]||0)})));
 const expired=lots.filter(l=>(!code||l.code===code)&&l.expiry<localToday()&&inRange(l.expiry));
 const records=movements.filter(m=>(!code||m.code===code)&&inRange(m.movementDate||new Date(m.createdAt).toLocaleDateString('sv-SE'))&&(!nhc||m.nhc?.toLowerCase().includes(nhc.toLowerCase()))&&(report!=='Historial de movimientos'||!professional||m.professional?.toLowerCase().includes(professional.toLowerCase()))&&(report!=='Consumo'||m.reason==='Suministro a pacientes'));
 const orderById=new Map(orders.map(o=>[o.id,o]));const orderRecords=orderLines.filter(l=>{const o=orderById.get(l.orderId);return !!o&&(!code||l.code===code)&&inRange(o.date)&&(!professional||o.professional.toLowerCase().includes(professional.toLowerCase()));});
 const printFilters=[code?`Vacuna: ${vaccines.find(v=>v.code===code)?.name||code} (${code})`:'Todas las vacunas',report==='Reposición'?`Almacén: ${warehouse}`:`${report==='Caducadas'?'Caducidad':'Fecha del movimiento/pedido'}: ${from?formatDate(from):'sin inicio'} a ${to?formatDate(to):'sin fin'}`,(report==='Consumo'||report==='Historial de movimientos')&&nhc?`NHC: ${nhc}`:'',(report==='Historial de movimientos'||report==='Pedidos a proveedor')&&professional?`Profesional: ${professional}`:''];
 const printCount=report==='Reposición'?replenish.length:report==='Caducadas'?expired.length:report==='Pedidos a proveedor'?orderRecords.length:records.length;
 return <section className="print-region reports-print-region"><PrintControls title={`Informe de ${report.toLowerCase()}`} filters={printFilters} count={printCount} notice={report==='Consumo'?`${records.reduce((n,m)=>n+m.quantity,0)} unidades suministradas · Historial cargado (hasta 1000 movimientos)`:report==='Historial de movimientos'||report==='Pedidos a proveedor'?'Historial cargado (hasta 1000 registros)':undefined}/><div className="report-tabs">{REPORTS.map(r=><button className={report===r?'selected':''} key={r} onClick={()=>setReport(r)}>{r}</button>)}</div><section className="panel report-filters"><label>Vacuna<select value={code} onChange={e=>setCode(e.target.value)}><option value="">Todas las vacunas</option>{vaccines.map(v=><option key={v.id} value={v.code}>{v.code} · {v.name}</option>)}</select></label>{report==='Reposición'?<label>Almacén<select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option>Todos</option>{WAREHOUSES.map(w=><option key={w}>{w}</option>)}</select></label>:<><label>{report==='Caducadas'?'Caducidad desde':'Desde'}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></>}{(report==='Consumo'||report==='Historial de movimientos')&&<label>NHC<input value={nhc} onChange={e=>setNhc(e.target.value)} placeholder="Filtrar por NHC"/></label>}{(report==='Historial de movimientos'||report==='Pedidos a proveedor')&&<label>Profesional (NIF)<input value={professional} onChange={e=>setProfessional(e.target.value)} placeholder="Filtrar por NIF"/></label>}<button className="secondary" onClick={()=>{setCode('');setFrom('');setTo('');setWarehouse('Todos');setNhc('');setProfessional('');}}>Limpiar filtros</button></section>
 {report==='Reposición'?<section className="panel"><div className="section-heading report-heading"><h2>Vacunas que hay que reponer</h2><span className="eyebrow">UNIDADES PARA ALCANZAR EL MÍNIMO</span></div>{!replenish.length?<p className="empty">No hay vacunas por debajo del mínimo para este filtro.</p>:<div className="table-wrap"><table><thead><tr><th>ALMACÉN</th><th>CÓDIGO VACUNA</th><th>CÓDIGO SIVAC</th><th>VACUNA</th><th>DISPONIBLES</th><th>MÍNIMO</th><th>UNIDADES A REPONER</th></tr></thead><tbody>{replenish.map(({v,w,stock,units})=><tr key={v.id+w}><td>{w}</td><td>{v.code}</td><td>{v.sivac}</td><td><strong>{v.name}</strong></td><td>{stock}</td><td>{v.minimum[w]}</td><td className="stock-number">{units}</td></tr>)}</tbody></table></div>}</section>:report==='Caducadas'?<section className="panel"><div className="section-heading report-heading"><h2>Lotes caducados</h2></div>{!expired.length?<p className="empty">No hay lotes caducados para este filtro.</p>:<div className="table-wrap"><table><thead><tr><th>CÓDIGO VACUNA</th><th>CÓDIGO SIVAC</th><th>VACUNA</th><th>LOTE</th><th>CADUCIDAD</th>{WAREHOUSES.map(w=><th key={w}>{w.toUpperCase()}</th>)}</tr></thead><tbody>{expired.map(l=><tr key={l.id}><td>{l.code}</td><td>{l.sivac}</td><td><strong>{l.name}</strong></td><td>{l.lot}</td><td>{formatDate(l.expiry)}</td>{WAREHOUSES.map(w=><td key={w}>{l.stocks[w]||0}</td>)}</tr>)}</tbody></table></div>}</section>:report==='Pedidos a proveedor'?<section className="panel"><div className="section-heading report-heading"><h2>Pedidos a proveedor</h2><span className="eyebrow">HISTORIAL CARGADO · ÚLTIMOS 1000</span></div>{!orderRecords.length?<p className="empty">No hay pedidos para los filtros seleccionados.</p>:<div className="table-wrap"><table><thead><tr><th>FECHA</th><th>PEDIDO</th><th>CÓDIGO VACUNA</th><th>CÓDIGO SIVAC</th><th>VACUNA</th><th>PEDIDAS</th><th>RECIBIDAS</th><th>ESTADO</th><th>PROFESIONAL</th></tr></thead><tbody>{orderRecords.map(l=>{const o=orderById.get(l.orderId)!;return <tr key={l.id}><td>{formatDate(o.date)}</td><td>{o.number}</td><td>{l.code}</td><td>{l.sivac}</td><td>{l.name}</td><td>{l.quantity}</td><td>{l.received}</td><td>{o.status}</td><td>{o.professional}</td></tr>;})}</tbody></table></div>}</section>:<><p className="form-hint">{report==='Consumo'?`${records.reduce((n,m)=>n+m.quantity,0)} unidades suministradas en el periodo seleccionado.`:'El historial distingue fecha del movimiento y fecha de registro.'} Datos privados del equipo con acceso mediante invitación.</p><MovementHistory movements={records} lots={lots} onSaved={onSaved}/></>}
 </section>;
}
