import {lazy,Suspense,useState} from 'react';
import {Plus,Search,RefreshCw,Syringe,Pencil,Trash2} from 'lucide-react';
import {WAREHOUSES,total,type Vaccine,type VaccineLot} from '../hooks/useInventory';
import PrintControls from './PrintControls';
import {balancesByCode,formatDate,localToday} from '../lib/inventory';
const EditVaccineForm=lazy(()=>import('./EditVaccineForm'));
const DeleteRecordDialog=lazy(()=>import('./DeleteRecordDialog'));
export default function VaccineInventory({vaccines,lots,registration,loading,onRegister,onRefresh}:{vaccines:Vaccine[];lots:VaccineLot[];registration:boolean;loading:boolean;onRegister:()=>void;onRefresh:()=>Promise<void>}){
 const[edit,setEdit]=useState<VaccineLot|null>(null),[remove,setRemove]=useState<VaccineLot|null>(null);const[search,setSearch]=useState(''),[warehouse,setWarehouse]=useState('Todos los almacenes');const balances=balancesByCode(lots),byCode=new Map(vaccines.map(v=>[v.code,v])),today=localToday();
 const match=(p:{name:string;code:string;sivac:string})=>`${p.name} ${p.code} ${p.sivac}`.toLowerCase().includes(search.toLowerCase());
 const filteredLots=lots.filter(l=>(match(l)||l.lot.toLowerCase().includes(search.toLowerCase())||!!l.scanCode?.toLowerCase().includes(search.toLowerCase()))&&(warehouse==='Todos los almacenes'||l.stocks[warehouse]>0));
 const filteredVaccines=vaccines.filter(v=>match(v)&&(warehouse==='Todos los almacenes'||(balances.get(v.code)?.[warehouse]||0)>0));const count=registration?filteredLots.length:filteredVaccines.length;
 return <><section className="panel inventory print-region"><PrintControls title={registration?'Registro de vacunas y lotes':'Inventario por vacuna'} filters={[warehouse,search?`Búsqueda: ${search}`:'Sin búsqueda']} count={count} disabled={loading||!!edit||!!remove}/><div className="section-heading"><div className="title-inline"><h2>{registration?'Registro de vacunas y lotes':'Inventario por vacuna'}</h2><span className="count">{registration?lots.length:vaccines.length}</span></div><button className="secondary" onClick={onRegister}><Plus size={17}/> Registrar vacuna</button></div><div className="toolbar"><div className="search"><Search size={17}/><input aria-label="Buscar vacunas" placeholder={registration?'Vacuna, código, SIVAC o lote…':'Vacuna, código o SIVAC…'} value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filtrar por almacén" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option>Todos los almacenes</option>{WAREHOUSES.map(w=><option key={w}>{w}</option>)}</select><button className="icon-button" aria-label="Actualizar inventario" onClick={onRefresh}><RefreshCw size={17}/></button></div>
 <div className="table-wrap"><table><thead><tr><th>CÓDIGO VACUNA</th><th>CÓDIGO SIVAC</th><th>VACUNA</th>{registration&&<><th>LOTE</th><th>CADUCIDAD</th></>}{WAREHOUSES.map(w=><th key={w}>{w.toUpperCase()}<small className="cell-small">STOCK DISPONIBLE{registration?' / MÍNIMO':''}</small></th>)}<th>TOTAL</th>{registration&&<th className="no-print">ACCIONES</th>}</tr></thead><tbody>{registration?filteredLots.map(l=><tr key={l.id}><td>{l.code}</td><td>{l.sivac}</td><td><strong>{l.name}</strong></td><td>{l.lot}{l.scanCode&&<small className="cell-small" title={l.scanCode}>QR / barras asociado</small>}</td><td><span className={l.expiry<today?'stock-badge low':''}>{formatDate(l.expiry)}</span>{l.expiry<today&&<small className="cell-small">Caducado</small>}</td>{WAREHOUSES.map(w=><td key={w}><strong>{l.stocks[w]||0}</strong><small className="cell-small">Mín. vacuna: {byCode.get(l.code)?.minimum[w]??0}</small></td>)}<td>{total(l)}</td><td className="no-print"><div className="table-actions"><button className="icon-button" aria-label={`Modificar ${l.name} lote ${l.lot}`} title="Modificar" onClick={()=>setEdit(l)}><Pencil size={16}/></button><button className="icon-button delete-icon" aria-label={`Eliminar ${l.name} lote ${l.lot}`} title="Eliminar" onClick={()=>setRemove(l)}><Trash2 size={16}/></button></div></td></tr>):filteredVaccines.map(v=>{const b=balances.get(v.code)||{};return <tr key={v.id}><td>{v.code}</td><td>{v.sivac}</td><td><strong>{v.name}</strong></td>{WAREHOUSES.map(w=><td key={w}><span className={(b[w]||0)<v.minimum[w]?'stock-badge low':'stock-number'}>{b[w]||0}</span></td>)}<td className="stock-number">{WAREHOUSES.reduce((n,w)=>n+(b[w]||0),0)}</td></tr>;})}</tbody></table></div>
 {!count&&<div className="empty"><Syringe size={30}/><h3>{loading?'Cargando inventario…':vaccines.length?'No hay resultados para este filtro':'Empieza con tu primera vacuna'}</h3><p>Registra código, SIVAC, lote, caducidad y unidades por almacén.</p></div>}<footer className="table-footer">{count} {registration?'lotes':'vacunas'}<span>{registration?'Mínimos por vacuna; unidades por lote':'Unidades agregadas de todos los lotes · Actualización cada 15 s'}</span></footer></section>{edit&&byCode.get(edit.code)&&<Suspense fallback={null}><EditVaccineForm lot={edit} vaccine={byCode.get(edit.code)!} onClose={()=>setEdit(null)} onSaved={onRefresh}/></Suspense>}{remove&&<Suspense fallback={null}><DeleteRecordDialog title="Eliminar registro de vacuna" description={`Se eliminará el lote ${remove.lot} de ${remove.name}, todas sus unidades disponibles, sus movimientos y sus recepciones. Las cantidades recibidas se descontarán de los pedidos, que quedarán pendientes cuando corresponda. Los otros lotes se conservarán.`} fn="deleteVaccineLot" params={{id:remove.id,cascade:true}} onClose={()=>setRemove(null)} onSaved={onRefresh}/></Suspense>}</>;
}
