import logo from './logo.png';
import {lazy,Suspense,useState} from 'react';
import {Ticket,Syringe,ClipboardList,ArrowLeftRight,Boxes,AlertTriangle,ChevronRight,FileText,ShoppingCart} from 'lucide-react';
import {WAREHOUSES,useInventory} from './hooks/useInventory';
import Insights,{getAlerts} from './components/Insights';
import VaccineInventory from './components/VaccineInventory';
import MovementHistory from './components/MovementHistory';
const InventoryForm=lazy(()=>import('./components/InventoryForm'));
const Reports=lazy(()=>import('./components/Reports'));
const TABS=[{label:'Registro de vacunas',icon:ClipboardList},{label:'Inventario',icon:Boxes},{label:'Pedidos',icon:ShoppingCart},{label:'Movimientos',icon:ArrowLeftRight},{label:'Informes',icon:FileText}];
const Orders=lazy(()=>import('./components/Orders'));
const InvitationManager=lazy(()=>import('./components/InvitationManager'));
export default function Dashboard({access,onLogout}:{access:{admin?:boolean;nif?:string};onLogout:()=>Promise<void>}){
 const{vaccines,lots,movements,orders,orderLines,receipts,loading,error,refresh}=useInventory();const[tab,setTab]=useState('Inventario'),[modal,setModal]=useState<'vaccine'|'movement'|null>(null);const alerts=getAlerts(vaccines,lots);
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#"><span className="brand-icon"><Syringe size={23}/></span>Gestión de STOCK VACUNAS<span className="brand-dot">.</span></a><span className="workspace-label">GESTIÓN DE VACUNAS</span><nav>{TABS.map(({label,icon:Icon})=><button key={label} aria-label={label} title={label} className={tab===label?'active':''} onClick={()=>setTab(label)}><Icon size={19}/><span>{label}</span>{tab===label&&<ChevronRight className="nav-arrow" size={16}/>}</button>)}{access.admin&&<button className={tab==='Invitaciones'?'active':''} onClick={()=>setTab('Invitaciones')} aria-label="Invitaciones"><Ticket size={19}/><span>Invitaciones</span></button>}</nav><div className="sidebar-note"><Boxes size={27}/><h3>Medicina Preventiva y Control de la Infección</h3><p>{WAREHOUSES.map(w=><span className="cell-small" key={w}>{w}</span>)}</p></div><div className="store-profile"><span>V</span><div><strong>Inventario de vacunas</strong><small>Profesional: {access.nif}</small></div></div></aside><main><header className="topbar"><img className="app-logo" src={logo} alt="Logo corporativo"/><span>Gestión <ChevronRight size={13}/><strong>{tab}</strong></span><button className="secondary logout-button" onClick={onLogout}>Cerrar sesión</button><span className="date">{new Date().toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}</span></header><div className="page-content"><div className="page-heading"><div><span className="eyebrow">TRAZABILIDAD POR LOTE Y ALMACÉN</span></div>{access.admin&&<button className="secondary" onClick={()=>setTab('Invitaciones')}><Ticket size={17}/> Invitar usuarios</button>}<button className="primary" disabled={!lots.length} onClick={()=>setModal('movement')}><ArrowLeftRight size={17}/> Registrar movimiento</button></div>{error&&<p className="error" role="alert">{error} <button onClick={refresh}>Reintentar</button></p>}
 <div className="metrics">{WAREHOUSES.map(w=><div className="metric" key={w}><span>{w}<Boxes size={19}/></span><strong>{lots.reduce((n,l)=>n+(l.stocks[w]||0),0).toLocaleString('es-ES')}<small>unidades disponibles</small></strong></div>)}<div className="metric warning"><span>Alertas de stock bajo<AlertTriangle size={19}/></span><strong>{alerts.length}<small>vacuna / almacén por reponer</small></strong></div></div>
 {(tab==='Registro de vacunas'||tab==='Inventario')&&<VaccineInventory vaccines={vaccines} lots={lots} registration={tab==='Registro de vacunas'} loading={loading} onRegister={()=>setModal('vaccine')} onRefresh={refresh}/>}
 {tab==='Inventario'&&<Insights vaccines={vaccines} lots={lots} movements={movements} onMovement={()=>setModal('movement')}/>}{tab==='Movimientos'&&<MovementHistory movements={movements} lots={lots} onSaved={refresh}/>} {tab==='Informes'&&<Suspense fallback={<p className="empty">Cargando informes…</p>}><Reports vaccines={vaccines} lots={lots} movements={movements} orders={orders} orderLines={orderLines} onSaved={refresh}/></Suspense>}
 {tab==='Pedidos'&&<Suspense fallback={<p className="empty">Cargando pedidos…</p>}><Orders vaccines={vaccines} lots={lots} orders={orders} lines={orderLines} receipts={receipts} movements={movements} nif={access.nif||''} onSaved={refresh}/></Suspense>}{tab==='Invitaciones'&&access.admin&&<Suspense fallback={null}><InvitationManager/></Suspense>}<footer className="page-footer"><span>Gestión de STOCK VACUNAS. <span>Control de existencias, lote a lote.</span></span><span>Acceso mediante invitación · Registro por profesional.</span></footer></div></main>{modal&&<Suspense fallback={null}><InventoryForm mode={modal} lots={lots} vaccines={vaccines} onClose={()=>setModal(null)} onSaved={refresh}/></Suspense>}</div>;
}
